name: "fuzz"
version: "0.1.0"
usage: "Automated property-based testing for Helm charts"
description: |-
  Helm Fuzz is a chaos testing tool that automatically detects crashes in Helm charts.
  It generates thousands of randomized, valid-schema values.yaml inputs and attempts to
  render the chart. If a specific set of values causes the template engine to panic or
  produce error messages, the tool identifies it and minimizes the input to the smallest
  possible reproduction case.
command: "$HELM_PLUGIN_DIR/helm-fuzz"
hooks:
  install: "cd $HELM_PLUGIN_DIR && ./install.sh"
  update: "cd $HELM_PLUGIN_DIR && ./install.sh"
